#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/AbyssinicaSIL-Regular.ufo -l source/logs/norm.log

# Building composites - needs to be done after normalization or may complain due to bad anchor coordinates
# psfbuildcomp -i source/composites.txt source/AbyssinicaSIL-Regular.ufo -l source/logs/comps.log

# psfsetpsnames -i source/glyph_data.csv source/AbyssinicaSIL-Regular.ufo -l source/logs/psnames.log
# psfsetglyphorder --header sort_final -i source/glyph_data.csv source/AbyssinicaSIL-Regular.ufo -l source/logs/sortorder.log
