#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/AbyssinicaSIL-Regular.ufo -l source/logs/norm.log
wait

echo "Updating woff metadata xml file..."
psfmakewoffmetadata -q -n AbyssinicaSIL -i org.sil.fonts source/*-Regular.ufo -o "source/AbyssinicaSIL-WOFF-metadata.xml"

echo "Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none -p backup=False --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/*-Regular.ufo


# Building composites - needs to be done after normalization or may complain due to bad anchor coordinates
# psfbuildcomp -i source/composites.txt source/AbyssinicaSIL-Regular.ufo -l source/logs/comps.log

# psfsetpsnames -i source/glyph_data.csv source/AbyssinicaSIL-Regular.ufo -l source/logs/psnames.log
# psfsetglyphorder --header sort_final -i source/glyph_data.csv source/AbyssinicaSIL-Regular.ufo -l source/logs/sortorder.log

echo "Building internal fea..."
psfmakefea -q -o source/AbyssinicaSIL-Regular.ufo/features.fea -l AbyssinicaSIL-Regular-psfmakefea.log -i source/opentype/master.feax source/*-Regular.ufo &
wait
